In [1]:
import io
import pandas as pd
from google.cloud import storage

In [2]:
service_account_key = "dags/keys/gcs.json"
bucket_name = "raw-furniture-data"
client = storage.Client.from_service_account_json(service_account_key)
bucket = client.bucket(bucket_name)

In [3]:
blobs = bucket.list_blobs()
for blob in blobs:
    print(blob.name)

customers_raw.csv
furniture_raw.csv
orders_raw.csv
sales_raw.csv

In [4]:
customers_blob = bucket.blob("customers_raw.csv")
customers_bytes = customers_blob.download_as_bytes()
customers_df = pd.read_csv(io.BytesIO(customers_bytes))

furniture_blob = bucket.blob("furniture_raw.csv")
furniture_bytes = furniture_blob.download_as_bytes()
furniture_df = pd.read_csv(io.BytesIO(furniture_bytes))

orders_blob = bucket.blob("orders_raw.csv")
orders_bytes = orders_blob.download_as_bytes()
orders_df = pd.read_csv(io.BytesIO(orders_bytes))

sales_blob = bucket.blob("sales_raw.csv")
sales_bytes = sales_blob.download_as_bytes()
sales_df = pd.read_csv(io.BytesIO(sales_bytes))

In [5]:
customers_df.head()

,customer_id,first_name,last_name,email,country,signup_date
0,df3e9ab4-9b63-4a4c-817d-79e272768055,Bob,Smith,user0@example.com,usa,05/23/2023
1,d459dd95-6504-41b7-a9d6-42f6a022a821,Bob,Lee,user1@example.com,UK,27-08-2024
2,a046b761-8f37-4f7c-9f84-461efc1a1c2d,Alice,Smith,NaN,USA,2024-09-08
3,9f2b7a3c-7c35-4d74-aceb-4d24a4784932,Diana,Lee,user3@example.com,UK,14-08-2023
4,3368df91-aed0-44d5-b878-88ef63269fee,Ethan,Martin,user4@example.com,USA,15-12-2023

In [6]:
customers_df.describe()

,customer_id,first_name,last_name,email,country,signup_date
count,210,210,210,169,210,210
unique,200,8,7,162,13,188
top,8bd8d916-976c-4f76-9051-d3f63b7f6f7b,Bob,Anderson,user175@example.com,UK,21-02-2024
freq,2,28,33,2,26,3

In [7]:
furniture_df.head()

,furniture_id,product_name,category,material,base_price
0,0a13d929-d6ca-4aa9-84ec-d5ec729857ad,Chair Model 0,Table,NaN,NaN
1,bd955bc0-7b72-46bc-af8f-2da5fdd85f53,Table Model 1,Chair,Glass,590.34
2,f750b398-c0ad-48c8-8457-24d91f10d311,Cabinet Model 2,CHAIR,Wood,NaN
3,f398d9f3-dbd6-4552-b877-f989e9d71f63,Chair Model 3,Bed,Metal,503.05
4,075ed897-6aa8-47a5-90e0-c9320eb4d667,Sofa Model 4,Cabinet,Wood,NaN

In [8]:
furniture_df.describe()

        base_price
count    27.000000
mean    808.039259
std     458.396016
min     129.430000
25%     436.255000
50%     672.460000
75%    1218.240000
max    1486.930000

In [9]:
orders_df.head()

,order_id,customer_id,order_date,order_status,customer_country
0,5a12fc1e-7f21-47f2-b667-093bedba40fb,e985771d-fd53-4841-89c9-8c91c7a4abe0,10/07/2023,CANCELLED,canada
1,ccbc9af5-350d-43a1-babd-a803be276860,4b17bb1a-cfc7-4a15-be33-16f8fb5a8ac5,2024-03-23,PLACED,canada
2,51fdf618-8b8a-4a8e-834a-4cc7e31b6a39,574e0403-f217-4f3f-8d92-5006ace447b1,24-12-2023,PLACED,Canada
3,ff5758f1-ac8e-4bce-8f2c-ce0ea983fa4c,9179e8fb-e577-4d9c-b78a-dc05d5736ece,2024-02-10,DELIVERED,Canada
4,6f82c92d-e0e0-471e-94ab-563554653ae7,08c65964-6c0b-420b-9ad9-ee5acebcec3c,2023-03-25,DELIVERED,uk

In [10]:
orders_df.describe()

,order_id,customer_id,order_date,order_status,customer_country
count,10000,10000,10000,10000,10000
unique,10000,200,2173,4,30
top,5a12fc1e-7f21-47f2-b667-093bedba40fb,7b1520fd-b50e-40e6-a78c-67afc5ac289f,03/22/2023,SHIPPED,UK
freq,1,114,13,2579,610

In [11]:
sales_df.head()

,sale_id,order_id,furniture_id,quantity,discount,total_price
0,2097e8b8-a983-4af1-be95-e91aec0753ac,5a12fc1e-7f21-47f2-b667-093bedba40fb,01553bae-cef4-419c-aab9-95d361217449,3,0.09,NaN
1,bc95a056-1d8d-4ad4-9b49-6776962c0b3c,5a12fc1e-7f21-47f2-b667-093bedba40fb,be1275b7-1471-48cb-939c-1fb75c3a3401,2,0.17,NaN
2,6cfb5e33-98dc-4d9c-ae2d-1e1a7da47da1,5a12fc1e-7f21-47f2-b667-093bedba40fb,0a13d929-d6ca-4aa9-84ec-d5ec729857ad,-1,0.21,NaN
3,2bd265e7-5ece-4c88-a293-b2a6992494ba,5a12fc1e-7f21-47f2-b667-093bedba40fb,3564ce00-7d9a-4118-ba82-fe1cb3b5e134,3,0.13,NaN
4,84221d61-acb6-4238-a018-2510ff48fe9c,ccbc9af5-350d-43a1-babd-a803be276860,138412f5-7c12-447d-8b3d-1ad11cd1bd8d,-1,0.28,NaN

In [12]:
sales_df.describe()

           quantity      discount  total_price
count  27176.000000  27176.000000          0.0
mean       1.224426      0.149745          NaN
std        1.474222      0.086728          NaN
min       -1.000000      0.000000          NaN
25%        0.000000      0.070000          NaN
50%        1.000000      0.150000          NaN
75%        2.000000      0.230000          NaN
max        3.000000      0.300000          NaN